### PR TITLE
Pick up staging environment overrides when generating demo configs

### LINKED ISSUE #9: Use /_status/ping for liveness, and /_status/check for readiness
In the configs, start making use of both liveness and readiness.

For background, see https://github.com/canonical-web-and-design/ubuntu.com/issues/9027

### PR DESCRIPTION
**Pull request by jpmartinspt**
Fixes https://github.com/canonical-web-and-design/demos.haus/issues/13

### CODE REVIEW

**Comment by sowasred2012** [comment]
@jkfran could you review this one pls?

**Review by jkfran — COMMENTED** [review]
Hey Joao, I think it makes sense for demos but not local QAs. I think it needs to be only for demos. WDYT?

**Comment by jpmartinspt** [comment]
@jkfran demos is probably all we want, I just updated.

**Review by jkfran — APPROVED** [review]
LGTM

**Pull request merged**
